//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note : IComparable
    {
        public int NoteId { get; set; }
        public int Priority { get; set; }
        public string Subject { get; set; }
        public string Details { get; set; }

        public int CompareTo(object obj)
        {
            Note sortThis = obj as Note;

            if (sortThis != null)
            {
                return this.Priority.CompareTo(sortThis.Priority);
            }
            else
            {
                throw new ArgumentException();
            }
        }
    }
}
